language: java
jdk: openjdk11
cache:
  directories:
  - "$HOME/.m2"

branches:
  only:
    - master
    - temp

matrix:
  include:
    - os: linux
      dist: bionic
      env: OPENJDK_OS=linux
    - os: osx
      env: OPENJDK_OS=mac
  #    - os: windows
  #      env: OPENJDK_OS=windows
  allow_failures:
    - os: linux
    - os: osx

#addons:
#  apt:
#    packages:
#      - xvfb

before_install:
  - cp .travis/settings.xml $HOME/.m2/settings.xml
  - source install-jdk.sh --url "https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=hotspot&os=$OPENJDK_OS&arch=x64&release=latest&heap_size=normal&type=jdk"
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export DISPLAY=:99; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then Xvfb $DISPLAY & fi

deploy:
  - provider: script
    script: bash .travis/deploy-linux.sh
    skip_cleanup: true
    on:
      os: linux

#  - provider: script
#    script: bash .travis/deploy-macosx.sh
#    skip_cleanup: true
#    on:
#      os: osx

#  - provider: script
#    script: cmd .travis/deploy-windows.cmd
#    skip_cleanup: true
#    on:
#      os: windows

