matrix:
  include:
    - os: linux
      dist: bionic
      env: OPENJDK_OS=linux
    - os: osx
      env: OPENJDK_OS=mac
#    - os: windows
#      env: OPENJDK_OS=windows

language: java
jdk: openjdk11
cache:
  directories:
  - "$HOME/.m2"

addons:
  apt:
    packages:
      - xvfb

before_install:
  - source install-jdk.sh --url "https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=hotspot&os=$OPENJDK_OS&arch=x64&release=latest&heap_size=normal&type=jdk"
  - cp .travis/settings.xml $HOME/.m2/settings.xml
  - export DISPLAY=:99
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then Xvfb $DISPLAY \&; fi

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] || [ "$TRAVIS_OS_NAME" = "osx" ]; then rm -rf target/jlink; fi

deploy:
  - provider: script
    skip_cleanup: true
    script: bash .travis/deploy-linux.sh
    on:
      os: linux

  - provider: script
    skip_cleanup: true
    script: bash .travis/deploy-macosx.sh
    on:
      os: osx

#  - provider: script
#    skip_cleanup: true
#    script: cmd .travis/deploy-windows.cmd
#    on:
#      os: windows

