name: Avereon Xenon CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch sources
      uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Build & Test & Deploy
      env:
        AVN_GPG_PASSWORD: ${{ secrets.AVN_GPG_PASSWORD }}
        AVN_KEYSTORE_PASSWORD: ${{ secrets.AVN_KEYSTORE_PASSWORD }}
        AVN_REPO_USERNAME: ${{ secrets.AVN_REPO_USERNAME }}
        AVN_REPO_PASSWORD: ${{ secrets.AVN_REPO_PASSWORD }}
      run: |
        export DISPLAY=:99
        Xvfb ${DISPLAY} -screen 0 1920x1080x24 -nolisten unix &
        gpg --quiet --batch --yes --decrypt --passphrase=$AVN_GPG_PASSWORD --output .github/avereon.keystore .github/avereon.keystore.gpg
        mvn deploy -B -U -V --settings .github/settings.xml --file pom.xml
        .github/deploy/ci-deploy.sh
