group: ${project.groupId}
artifact: ${project.artifactId}
version: ${project.version}
timestamp: ${project.timestamp}

icon: http://www.xeomar.com/images/icons/${project.artifactId}.png
name: ${project.name}
provider: ${project.organization.name}
inception: ${project.inceptionYear}

summary: Java application platform
description: ${project.description}
copyright:
  summary: All rights reserved.
license:
  summary: ${project.name} comes with ABSOLUTELY NO WARRANTY. This is open software, and you are welcome to redistribute it under certain conditions.

maintainers:
  - !!com.xeomar.util.Maintainer
    name: Mark Soderquist
    email: mark.soderquist@xeomar.com
    roles:
      - Architect
    organization: Xeomar
    organizationUrl: http://xeomar.com/

contributors:
  - !!com.xeomar.util.Contributor
    name: Dan Langford

resources:
  head: "http://www.xeomar.com/download/product/${project.artifactId}/product.xml"
  pack: "http://www.xeomar.com/download/product/${project.artifactId}/product.zip"
