name: Avereon Xenon CI

on:
  push:
  schedule:
    - cron: '0 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch sources
      uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Build & Test & Deploy
      env:
        AVN_REPO_USERNAME: ${{ secrets.AVN_REPO_USERNAME }}
        AVN_REPO_PASSWORD: ${{ secrets.AVN_REPO_PASSWORD }}
      run: |
        export DISPLAY=:99
        Xvfb ${DISPLAY} -screen 0 1920x1080x24 -nolisten unix &
        mvn deploy -B -U -V --settings .github/settings.xml --file pom.xml
