name: Avereon Xenon Continuous

on:
  push:

env:
  AVN_GPG_PASSWORD: ${{ secrets.AVN_GPG_PASSWORD }}
  AVN_KEYSTORE_PASSWORD: ${{ secrets.AVN_KEYSTORE_PASSWORD }}
  AVN_REPO_USERNAME: ${{ secrets.AVN_REPO_USERNAME }}
  AVN_REPO_PASSWORD: ${{ secrets.AVN_REPO_PASSWORD }}
  DISPLAY: ":99"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Fetch sources
      uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Set up Secrets
      run: |
        mkdir "${HOME}/.ssh"
        gpg --quiet --batch --yes --decrypt --passphrase=$AVN_GPG_PASSWORD --output .github/avereon.keystore .github/avereon.keystore.gpg
        gpg --quiet --batch --yes --decrypt --passphrase=$AVN_GPG_PASSWORD --output $HOME/.ssh/id_rsa .github/id_rsa.gpg
        gpg --quiet --batch --yes --decrypt --passphrase=$AVN_GPG_PASSWORD --output $HOME/.ssh/id_rsa.pub .github/id_rsa.pub.gpg
        gpg --quiet --batch --yes --decrypt --passphrase=$AVN_GPG_PASSWORD --output $HOME/.ssh/known_hosts .github/known_hosts.gpg
    - name: Compile
      run: |
        Xvfb ${DISPLAY} -screen 0 1920x1080x24 -nolisten unix &
        mvn compile -B -U -V --settings .github/settings.xml --file pom.xml
    - name: Unit Test
      run: |
        Xvfb ${DISPLAY} -screen 0 1920x1080x24 -nolisten unix &
        mvn test -B -U -V --settings .github/settings.xml --file pom.xml
    - name: Deploy
      run: |
        Xvfb ${DISPLAY} -screen 0 1920x1080x24 -nolisten unix &
        mvn deploy -B -U -V --settings .github/settings.xml --file pom.xml -Dmaven.test.skip=true
