name: Avereon Xenon Continuous

on:
  push:

env:
  AVN_PRODUCT: "xenon"
  # The default release, should be overridden in the platform job
  AVN_RELEASE: "latest"
  # The default platform, should be overridden in the platform job
  AVN_PLATFORM: "linux"

  AVN_GPG_PASSWORD: ${{ secrets.AVN_GPG_PASSWORD }}
  AVN_KEYSTORE_PASSWORD: ${{ secrets.AVN_KEYSTORE_PASSWORD }}
  AVN_REPO_USERNAME: ${{ secrets.AVN_REPO_USERNAME }}
  AVN_REPO_PASSWORD: ${{ secrets.AVN_REPO_PASSWORD }}

  DISPLAY: ":99"
  GITHUB_REF: ${{ github.ref }}
  JAVA_VERSION: "13"
  MAVEN_PARMS: "-B -U -V --settings .github/settings.xml --file pom.xml"
  XVFB_PARMS: "-screen 0 1920x1080x24 -nolisten unix"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      JAVADOC_DEPLOY_PATH: "/opt/avn/store/latest/${AVN_PRODUCT}"
      JAVADOC_TARGET_PATH: "/opt/avn/web/product/${AVN_PRODUCT}/javadoc"
    steps:
      - name: Fetch sources
        uses: actions/checkout@v1

      - name: Configuration
        run: |
          source .github/workflows/config.sh

# TODO Is the virtual display needed for the build job
      - name: Set up Virtual Display
        run: |
          Xvfb ${{env.DISPLAY}} ${{env.XVFB_PARMS}} &

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}

#      - name: Compile
#        run: |
#          mvn ${{env.MAVEN_PARMS}} compile
#
#      - name: Unit Tests
#        run: |
#          mvn ${{env.MAVEN_PARMS}} test
#
#      - name: Deploy Maven Arifacts
#        run: |
#          mvn ${{env.MAVEN_PARMS}} deploy -Dmaven.test.skip=true
#
#      - name: Deploy JavaDoc
#        run: |
#          scp -B target/xenon-*-javadoc.jar travis@avereon.com:${{env.JAVADOC_DEPLOY_PATH}}/javadoc.jar 2>&1
#          if [ $? -ne 0 ]; then exit 1; fi
#          ssh -t travis@avereon.com "mkdir -p ${{env.JAVADOC_TARGET_PATH}};rm -rf ${{env.JAVADOC_TARGET_PATH}}/*;unzip -o ${{env.JAVADOC_DEPLOY_PATH}}/javadoc.jar -d ${{env.JAVADOC_TARGET_PATH}}"
#          if [ $? -ne 0 ]; then exit 1; fi

#  linux:
#    name: Linux Binaries
#    runs-on: ubuntu-latest
#    needs: build
#    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/stable' || github.base_ref == 'refs/heads/master' || github.base_ref == 'refs/heads/stable'
#    env:
#      AVN_PLATFORM: "linux"
#    steps:
#      - name: Fetch sources
#        uses: actions/checkout@v1
#
#      - name: Configuration
#        run: |
#          source .github/workflows/config.sh
#
#      - name: Set up Virtual Display
#        run: |
#          Xvfb ${{env.DISPLAY}} ${{env.XVFB_PARMS}} &
#
#      - name: Set up Java
#        uses: actions/setup-java@v1
#        with:
#          java-version: ${{env.JAVA_VERSION}}
#
##      - name: Build Binaries
##        run: |
##          mvn ${{env.MAVEN_PARMS}} clean verify -P testui,platform-specific-assemblies
#
#      - name: Build Binaries - No Tests
#        run: |
#          mvn ${{env.MAVEN_PARMS}} clean verify -P platform-specific-assemblies -Dmaven.test.skip=true
#
#      - name: Deploy Install Pack
#        run: |
#          scp -B target/*install.jar travis@avereon.com:${PRODUCT_DEPLOY_PATH} 2>&1
#
#      - name: Deploy Product Pack
#        run: |
#          scp -B target/*product.jar travis@avereon.com:${PRODUCT_DEPLOY_PATH} 2>&1
#
#      - name: Deploy Product Card
#        run: |
#          echo "PRODUCT_DEPLOY_PATH=${PRODUCT_DEPLOY_PATH}"
#          scp -B target/main/java/META-INF/*.card travis@avereon.com:${PRODUCT_DEPLOY_PATH} 2>&1
