name: Avereon Xenon for MacOSX

on:
  push:
  schedule:
    - cron: '0 0/3 * * *'

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Deploy
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/stable' || github.base_ref == 'refs/heads/master' || github.base_ref == 'refs/heads/stable'
        env:
          AVN_REPO_USERNAME: ${{ secrets.AVN_REPO_USERNAME }}
          AVN_REPO_PASSWORD: ${{ secrets.AVN_REPO_PASSWORD }}
          GITHUB_REF: ${{ github.ref }}
          MATRIX_OS: ${{ matrix.os }}
          TRAVIS_SSH_KEY: ${{ secrets.TRAVIS_SSH_KEY }}
          TRAVIS_SSH_PUB: ${{ secrets.TRAVIS_SSH_PUB }}
        run: .github/deploy/macosx-deploy.sh
